pluginManagement {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
    }
}

rootProject.name = 'mcef'

// SOLO incluir common y forge
include 'common'
include 'forge'

// EXCLUIR fabric y neoforge
// include 'fabric'
// include 'neoforge'
